import type { ActivityType } from "@/types/activity";
import { defaultHistoricalDateRange } from "./dateRange";
export function PlannerForm({ activityTypes }: { activityTypes: ActivityType[] }) {
  const dates = defaultHistoricalDateRange();
  return <main className="mx-auto max-w-5xl p-6 md:p-10">
    <header className="mb-8"><p className="font-semibold text-emerald-700">RouteMuse</p><h1 className="text-4xl font-bold">Plan your next outdoor route</h1><p className="mt-3 max-w-2xl text-slate-600">A foundation for recommendations grounded in your history and factual route-provider data.</p></header>
    <section className="mb-6 rounded-xl bg-white p-6 shadow-sm"><h2 className="mb-4 text-xl font-bold">Historical activity period</h2><div className="grid gap-4 md:grid-cols-2"><label>Start date<input type="date" defaultValue={dates.startDate}/></label><label>End date<input type="date" defaultValue={dates.endDate}/></label></div><button disabled className="mt-5 cursor-not-allowed rounded-lg bg-slate-300 px-5 py-3 text-slate-600">Connect with Strava — not implemented</button></section>
    <section className="mb-6 rounded-xl bg-white p-6 shadow-sm"><h2 className="mb-4 text-xl font-bold">Planning preferences</h2><fieldset disabled className="grid gap-4 opacity-70 md:grid-cols-2"><label>Location<input placeholder="Area or location"/></label><label>Activity type<select defaultValue=""><option value="">Select after connecting</option>{activityTypes.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Target distance (km), optional<input type="number"/></label><label>Target duration (minutes), optional<input type="number"/></label><label>Desired challenge, optional<select><option>Any</option><option>Easy</option><option>Moderate</option><option>Hard</option></select></label><label>Route shape, optional<select><option>Any</option><option>Loop</option><option>Out-and-back</option><option>Point-to-point</option></select></label></fieldset><p className="mt-4 text-sm text-slate-500">Planning controls will activate after activity import is implemented.</p></section>
    <section className="rounded-xl border-2 border-dashed border-emerald-200 p-8 text-center"><h2 className="text-xl font-bold">Recommendations</h2><p className="mt-2 text-slate-600">Provider-backed, personalized route candidates will appear here in a future release.</p></section>
  </main>;
}
